/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 client\public\untitled.glb -o client\src\components\UntitledModel.tsx 
*/

import * as THREE from 'three'
import React, { useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'TorusAction'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Torus: THREE.Mesh
    Plane: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/untitled.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions.TorusAction?.play()
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Torus" geometry={nodes.Torus.geometry} material={nodes.Torus.material} position={[1.388, 0, 1.189]} scale={1.656} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[-0.055, 0, 0.238]} scale={[2.815, 2.815, 2.184]} />
      </group>
    </group>
  )
}

useGLTF.preload('/untitled.glb')
